import React from 'react'
import { Post } from './Post'
import styles from './App.module.css';

export const Blog = () => {
    // fetch posts and display them
    return (
        <div className={styles.component}>
            <h1 className={styles.heading}>Short Stories</h1>
            <div className={styles.postbg}>
                <h2>The Three Seat Dilemma</h2>
                <p>&emsp; Walking in, he couldn’t tell where he was going to sit. Three chairs, three people, one girlfriend, one girlfriend’s sister; what was the ideal arrangement? Next to the girlfriend across from the sister? Next to the sister across from the girlfriend? Across from both the sister and the girlfriend? He considered his options. If he sat across from his girlfriend and next to the sister, it might risk seeming prematurely familiar with the sister. He had just met her right before the dinner, and now here he was, sitting less than three inches away from her and bumping elbows as they slurped on their soups! Not to mention, he had prepared for the meeting by putting on some nice, expensive cologne, and he would rather not signal incorrectly that he put on the cologne for the sister's enjoyment. No, that would not work. However, if he sat across from both the sister and the girlfriend, it would feel uncomfortably like an interrogation. Despite him and his girlfriend’s amorous relationship, ripening at around one month, the two sisters, three years apart, had known each other since the girlfriend was born. Although there is something particularly familiarizing about being a boyfriend to a girl, it can in no way replace a sisterly bond that is twenty-two years in the making. The girls would surely be more acquainted and familiar than he was to the sister, or for that matter, his own girlfriend. He considered the third option- sitting next to the girlfriend and across from the sister. Yes, he liked this option. Sitting adjacent to his girlfriend would demonstrate the confidence of the relationship, but at the same time leave room for interrogation by the sister. But would it seem too direct to sit across from the sister? What arrogance, what fortitude, he had to place himself directly in the center of the universe, the new boyfriend across from the sister, leaving the girlfriend alone to murmur on the diagonal. If he did this, he would undoubtedly have a fight to come home to later, a few wounds to cauterize, and a story to be brought up whenever the mildest irritation ensued, whether it be a dropped fork, a few minutes late to a reservation, or a sentence unheard as he scrolled through his daily timeline. But with only three options, he knew that this was the best one. Yes, he would place himself next to the girlfriend and across from the sister.

                <br/>&emsp; Luckily, it was not up to him. For when he had held the door open for the girls, they had stepped ahead and had already begun to sit down at the table. The girlfriend on the inside of the table facing away from the door, the sister moving towards the other side of the table facing the door, him moving to the spot next to the girlfriend, and the sister choosing a seat on the inside across from the girlfriend.
                 </p>
             </div>

             <div className={styles.postbg}>
                <h2>$700</h2>
                <p>The light hanging near the wall was flickering- not completely flickering, but it would shine for exactly 5 seconds, and flicker once. Wrapping the bulb was a red and blue mosaic glass shade, so tinted that the only way he knew it was flickering was by seeing the tiny light reflection on the 9 ball located underneath the bulb, on the billiards table, at a 25 degree angle to the light. Suddenly, the ball, and the image of the light for that matter, was obscured by a shoulder blade and a dull thud was followed by a sharp crack as the 9 ball collided into the 12, bounced off the wall, and tapped the 10. While the tap on the 10 was far from enough for anything momentous to occur, the 12 did get some persuasion, and decidedly rolled across to the other end of the table, stopping before it could be convinced to enter the left front pocket. Wondering whatever happened to the 9 ball, he allowed his eyes to approach the back of the table, but they became distracted when they saw the green felt illuminated in one spot more particularly than the others, in an ugly shade of tan.&nbsp;</p>
                <p><br/></p>
                <p>The light flickered.</p>
                <p><br/></p>
                <p>&ldquo;Aren&rsquo;t you going to say something?&rdquo;, the woman asked, sitting up straight with her arms by her sides. Her curly brown hair matched her vibrant, flowery dress, which stopped at the shoulders and created an aurora of friendliness and ease around her.&nbsp;</p>
                <p><br/></p>
                <p>&ldquo;Sorry, I just-&rdquo;, he looked up, &ldquo;I was just distracted by the light over there, it&rsquo;s flickering.&rdquo;</p>
                <p><br/></p>
                <p>The woman turned around for a second to see which light he was talking about, then turned back around and smiled reassuringly. &ldquo;Well it sounds like they should get that fixed, then. We wouldn&rsquo;t want anyone missing a shot, and,&rdquo; she gestured towards one of the men at the pool table who had yet to make a single shot, &ldquo;he looks like he is looking for any excuse he can get.&rdquo;</p>
                <p><br/></p>
                <p>He chuckled. She was funny. &ldquo;If you think he&rsquo;s having a rough day, you don&rsquo;t want to see me anywhere near that thing. The last time I played, I left the bar with $700 less than I came in with.&rdquo;&nbsp;</p>
                <p><br/></p>
                <p>Her eyes narrowed. &ldquo;Sounds like there&rsquo;s more to that story than you&rsquo;re letting on. You&rsquo;ll have to tell me the rest next time.&rdquo;</p>
                <p><br/></p>
                <p>&ldquo;It&rsquo;d be a pleasure,&rdquo; he replied with a grin. &ldquo;Will you excuse me for a second?&rdquo; He walked to the bar to refill his beer. The bartender was a young, thin man with short, dark, curly hair, a beard, and not a single hurried bone in his body. He did, however, contain a few chatty ones, and proceeded to laugh with a group of regulars and even ventured to say another couple remarks to them, despite the man leaning against the bar and signaling universally that he was ready to order a drink. When the bartender did attend to him, he gathered no change of pace. He took the man&rsquo;s empty plastic cup, and instead of refilling it, tossed it into the trash, looked for another one, and realized that he was temporarily out of stock. He smiled apologetically, turned around, walked to the other end of the bar, squatted down, and opened the drawer that contained the plastic cups. Of course, he was mistaken, but luckily he had to try no more than four to reach his final destination. Finding the cups, he unwrapped the outer plastic, set the pile down, took off the top one victoriously, and refilled the man&rsquo;s beer to two-thirds beer, one third foam, and- after entering in his order to the machine containing the man&rsquo;s credit card information- handed him the cup triumphantly. Thanking the bartender, the man hurriedly walked back towards his table.</p>
                <p><br/></p>
                <p>However, he did not make it in time. In her spot at the table sat the next girl, a blonde with an impatient look on her face. Apologizing for the delay, he looked around the room, but the curly haired girl in the flower dress was nowhere to be found. After a mediocre conversation, the buzzer rang, and the girl was replaced by another, and then another, and yet another, until eventually, the rotation had been completed, and she was still nowhere to be found. Realizing he didn&rsquo;t even catch her name, he sighed and cursed the bartender under his breath. He finished his beer as the bar hollowed out, and stood up to leave. He stretched and took his jacket from the back of the chair, reliving the night&rsquo;s mistakes and thinking about the missed opportunity that happened. As he leaned back, he noticed a bit of ink scribbled on one of the paper napkins on the table. Picking it up, he examined it from a closer distance, and smiled as the words appeared to him.</p>
                <p><br/></p>
                <p><br/></p>
                <p>Sorry I had to run, but I had a great time with you tonight! Let&rsquo;s get dinner sometime soon and you can finish your $700 story :) XOXO</p>
                <p>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; -K_________ &nbsp;(XXX) XXX-XXXX</p>
            </div>

            <div className={styles.postbg}>
                <h2>The Locker Note</h2>
                <p>Today I was walking to third period, and out of the corner of my eye I saw Sarah looking from behind the locker at me. Or I thought I did. She might have been looking past me at Mark. Ugh, Mark is so popular, she probably was looking at him. She probably doesn&rsquo;t even know I exist. Maybe I can do something clever to get her attention. Wait! That&rsquo;s it! Since she sits in front of me in sixth period, I can &ldquo;forget my pencil&rdquo; one day and then ask her for one! That won&rsquo;t really stand out though. Ugh, I wish I could think of something funny to do. Maybe&hellip; nevermind. I was going to say maybe I could ask her what she&rsquo;s doing this weekend, but there isn&rsquo;t really a point since I won&rsquo;t ask her to do anything with me. Or maybe I will. Maybe I&rsquo;ll first ask her, &ldquo;What&rsquo;s up with you this weekend&rdquo;- err, I mean, &ldquo;What are your plans this weekend?&rdquo; Then, when she replies, I&rsquo;ll say something like &ldquo;You&rsquo;re missing one thing.&rdquo; (I give a little smirk) &ldquo;Me.&rdquo; HAHAHA just kidding I&rsquo;m not going to do that but I will ask her what she&rsquo;s doing, just to see. It&rsquo;s not like she&rsquo;ll give me a suggestion that she wants to hang out with me. Maybe she&rsquo;s hanging out with Mark. I did hear him say the other day that he saw Bailey when he was getting ice cream with his mom the other day. He said that Bailey was with her mom getting ice cream, and he was right behind her in line, and he told her &ldquo;you should try the new Mint Chocolate Chip Oreo flavor&rdquo;. I almost can&rsquo;t believe that hahaha- and her mom was there too! That&rsquo;s so embarrassing! But that&rsquo;s what Mark does, he does what he wants, not like me. He&rsquo;s probably hanging out with Sarah this weekend. Why doesn&rsquo;t she like me? I even said hey to her best friend Rylee last Wednesday after third period. Rylee even said hey back, and she seemed like she meant it too. Maybe I will write Rylee a note and tell her to give it to Sarah. What will the note say though? I can&rsquo;t just say &ldquo;I like you&rdquo;, that would seem weird and awkward. Wait, maybe&hellip; yes, that&rsquo;s what I&rsquo;ll do- I&rsquo;ll write her a note that says &ldquo;Have you been to the new ice cream shop? You should try the WillYouBeMyGirlfriend flavor&rdquo;. Yes, I will do that! My dad says that if there&rsquo;s ever a hard thing just count to three and do it without thinking. I&rsquo;ll do it! One&hellip;two&hellip;three&hellip;</p>
                <p><br/></p>
                <p>&hellip;</p>
                <p><br/></p>
                <p>Thank God, Rylee thought. Math class was finally over. One more period left and then she could go home and prepare for her sleepover with her best friend, Sarah. They didn&rsquo;t have any plans for the evening so far, but she knew they would be listening to the new (well, six months old, but does it ever get old?) One Direction album, and she couldn&rsquo;t wait. Walking out of the hallway, she passed Mark (god he is so cute!) and gave him a half smile, unsure whether a full one was too direct- after all, rumor has it that he was going to ask Erin to the dance, which is a total shame because everyone knows that Erin likes Kyle, and Kyle likes her back. Anyways, she couldn&rsquo;t get carried away right now; she had to go to her locker and walk all the way to the other end of the school for her art class which starts in five- no four- minutes. Abiding by her usual routine, she unpacked her bookbag, grabbed a couple of the larger books, put them back- forgetting that she had to enter the code to her locker- entered the code, opened it, grabbed her books again, and put them into the locker, all without noticing the small leaf of paper escaping the locker, which floated in the breeze that the door created, stayed in the air for approximately two and a half seconds, and landed, face down, at the edge of the hallway.</p>
            </div>

            <div className={styles.postbg}>
                <h2>Bible Study</h2>
                <p>Well there, it&rsquo;s done. That idiot is laid down to rest, for good god damnit. Talk about a fateful time. He&rsquo;s the one who &lsquo;ad a fateful time. Planned for it the day &lsquo;e decided to insult Trisha. Such a purdy, sweet thing, never &lsquo;urt a fly, and here Eddy is being loud, cussin&rsquo;, raisin&rsquo; cane all in front of &lsquo;er. Ain&rsquo;t no one ever taught &lsquo;im manners and not to act a fool in fron&rsquo; of a decen&rsquo; woman? That&rsquo;s what I tol&rsquo; &lsquo;im at least. Then, &lsquo;e said &lsquo;e had been raised right, but &lsquo;e never heard nowhere that any girl of mine was decent, &lsquo;specially not that overweight hog Trisha. Said &lsquo;e&rsquo;d feed &lsquo;er some pig slop next time &lsquo;e saw &lsquo;er, if she could manage to get out the door. Where&rsquo;s that shovel? Found it. Yep, &lsquo;e&rsquo;s gon&rsquo; regret what &lsquo;e said now, for damn sure. Or &lsquo;e already is regrettin&rsquo; it. Prolly so far deep in the pits of &lsquo;ell that &lsquo;e can feel the devil&rsquo;s cock stickin&rsquo; out &lsquo;is throat. Serves &lsquo;im right, that sack of shit. Here, one more pile then I can toss the piece of shit in. There, &lsquo;e&rsquo;s in. Load the dirt back up. Pat it down. Zip. Sssssss. That serves &lsquo;im right.&nbsp;</p>
                <p><br/></p>
                <p>&hellip;</p>
                <p><br/></p>
                <p>Trish&rsquo; tellin&rsquo; me I need to go to Bible Study. Sayin&rsquo; I ain&rsquo;t been actin&rsquo; right. Shoot, of course I ain&rsquo;t been actin&rsquo; right, I just. I ain&rsquo;t complainin&rsquo; though. She needs to lighten up an&rsquo; let a man be a man. So what I ain&rsquo;t actin&rsquo; right. I&rsquo;ll act right soon enough. Just needs some more time. Guess a man can&rsquo;t get no time. Guess &lsquo;e just &lsquo;as to be perfec-ly normal all the time, perfec-ly fine and dandy. Always happy. Women are always happy and &lsquo;spect everyone else to ac&rsquo; just like &lsquo;em. Well I&rsquo;ll go. I don&rsquo;t wanna go, but I will just to prove I&rsquo;m actin&rsquo; right. At least to prove I&rsquo;m tryin&rsquo; a ac&rsquo; right. Where&rsquo;s my keys. God damnit, left &lsquo;em inside. Just left my keys inside. Woman ain&rsquo;t never hear a thing I say- I said I just left my damn keys inside. Get in the truck. Turn the keys. Go to the pastor&rsquo;s. Where&rsquo;s &lsquo;e live again. South Ridge Run, that&rsquo;s right. Five minutes from the church, prolly walks there on Sunday mornin&rsquo;. Prolly can hear the choir on &lsquo;is sick days. Here we go. This one. Ring the doorbell.</p>
                <p><br/></p>
                <p>Good to see ya. Yep, good to see you too. Mac, how&rsquo;s the wife. Good to see ya, Phil. What&rsquo;s on the plate for today. Psalms. Easy. One of my favorite books. Know all the words. David cryin&rsquo; out to the Lord. Father, I &lsquo;ave sinned. Murdered &lsquo;is best friend. Wanted &lsquo;is wife for &lsquo;imself, so sent Eddy out to the battle- I mean. Sent &lsquo;is friend righ&rsquo; out to the battlefiel&rsquo;. &lsquo;e don&rsquo;t seem like too bad a fella though, David just wanted &lsquo;is wife for &lsquo;imself. Lord punished &lsquo;im by killin&rsquo; &lsquo;is firs&rsquo; child. I got two kids, I&rsquo;m fine. Healthy as a &lsquo;are. Guess anyone can &lsquo;ave healthy kids though. Eddy had two. Michael and Ashton. Prolly haven&rsquo;t &lsquo;eard the news yet. Can&rsquo;t think about all that. &lsquo;e had it comin&rsquo; to &lsquo;im, talkin&rsquo; shit about Trish. Deserved everything that came to &lsquo;im. What&rsquo;s pastor talking about. Am I okay, &lsquo;course I&rsquo;m okay. Stop looking at me, I&rsquo;m fine. Yes, I&rsquo;m feelin&rsquo; alright. Yes, I&rsquo;m actin&rsquo; right, get back to the story. Awful nice story. What happened to David after that? Make up with the Lord? Bless for the res&rsquo; of &lsquo;is life? Don&rsquo;t pick up that. Prolly just a telemarketer. Don&rsquo;t pick that up. It&rsquo;ll kill me. Eddy&rsquo;s dead. Found &lsquo;is body buried near the Slater ranch. Ten miles up the road. Are you sure you&rsquo;re alright? I need to go. Can&rsquo;t take this right now. David can wait. I just need to- yes I&rsquo;m leavin&rsquo;. Trisha needs me to pick up some- no I&rsquo;m fine. Just a little dizzy, y&rsquo;all go on without me. I can just be back right around the corner. Swear. Nothing I need too far without my keys and- I&rsquo;ll just be gone after I get back we&rsquo;ll finish learnin&rsquo; bout Eddy. I mean David, god dammit. No, I shouldn&rsquo;t&rsquo;ve said that, Lord wouldn&rsquo; like &lsquo;is name taken in vain. I don&rsquo;t either, and that goes for me and my wife. Deserved every last bit of what came to &lsquo;im. Matter a fac&rsquo;, I&rsquo;m goin&rsquo; to check on &lsquo;er. Probably in a mess right now, hearin&rsquo; about- no, I don&rsquo;t need to. I&rsquo;m just feeling a little- maybe I can just sit down for half a minut-...</p>
                <p><br/></p>
                <p><br/></p>
            </div>

            <div className={styles.postbg}>
                <h2>King Alexander</h2>
                <p>It was 9pm when King Alexander of Constantinople sat down on his throne. One must wonder how I could remember this time. After all, many things happen at all sorts of times of day without me remembering. For example, yesterday I ate dinner, but I had no inclination to look at the time. I simply ate because I was hungry. Is that an insane thing to do? I think not. Many people will have set schedules for eating- I do not like to let something as silly as a timepiece dictate when I do what I do, nor will I allow it to influence me in the slightest. I am so passionate about this that I threw away all my clocks. I do not associate with the things, lest they penetrate my subconscious, worm their way into my habits, and dig their shackles into my wrists and ankles. You find me a silly man. You say that there is no way that I live my life without using a clock or looking at the time. However, you would be completely correct in this statement but I refuse to acknowledge your condescension. Of course I use a timepiece, for I am a man of matters and affairs and I have no reason to neglect something as important as to alert me when I am running late to another meeting and am in a state of utter regret and dismay to inform you that I must leave your presence at the current moment, but I send my utmost regards and wish to see you soon.&nbsp;</p>
                <p><br/></p>
                <p>But of course I remember this time. I remember this time because as exactly the ninth and final bell of the clock tolled, King Alexander sat on his throne, and decreed that he will be taking a trip to the East to meet with the ruler in Baku. Additionally, he made sure to alert everyone of the coincidence between the number of days of his trip and the time of day (which, although I claimed that it was because of the clock toll, it is more likely that this is probably the reason I remember the time so well), by saying,&nbsp;</p>
                <p><br/></p>
                <p>&ldquo;My council. It is said that one cannot be surer of catastrophe as when a man is troubled by flutters of consciousness, resolutions, and clarity; realizes the need to reveal an innermost inkling- and resolves not to say it. One of two things is certain. He either begins to develop a thin layer around his heart, a layer that separates him from his community. This layer makes it harder for him to reveal his inkling and the layer starts to harden and turns into a shell of resentment. We&rsquo;ve seen this with many Kings, who, night by night, stirred restlessly, finding consolation only in the dampening power of spirits and women. The other alternative is that he realizes at a later time that he needs to reveal himself, but is never given the opportunity, or it is already too late.&nbsp;</p>
                <p><br/></p>
                <p>&ldquo;I refuse to be one of these two unfortunate souls. Many nights have been spent next to my chamber&rsquo;s window. I gazed into the sky and contemplated the city in which I rule. It feels like the center of the world sometimes. When I was a child, I dreamed of being a crusader. I was going to be Raymond de Saint-Gilles, traveling the world and conquering all that the eye could see for my country. But suddenly, I was no longer a child. I was responsible for others and needed to develop myself for the throne. The dream of Alexander de Saint-Gilles had dimmed and was all but forgotten.</p>
                <p><br/></p>
                <p>&ldquo;However, I received a message from my old friend King Oblai of Baku that invited me to his kingdom. Immediately I rejected it. As your king, I need to be present so that all matters of politics and defense can be attended to. If I am gone, who will direct the city? Who will lead the council? Who will plan our future conquests and military advances? But I realized that perhaps I have too tight of a grip. I realize now that I need to trust that Constantinople will be safe in my absence. After all, I am getting older. My son, the Prince, is ever by my side and being trained in areas of combat and leadership. I will not be around forever, and he will inherit the throne one day. Therefore, I have decided, that just as the clock has struck nine times, I will indeed be gone for nine days.&rdquo;</p>
                <p><br/></p>
            </div>
        </div>
    )
}
